import { createIdFactory, KleinSdkError } from '../core/index.js';
import { resolveKleinToolTheme } from '../theme/index.js';
import { KLEIN_MONO_FONT_STACK, KLEIN_UI_FONT_STACK } from '../theme/index.js';
import type { KleinToolThemeInput } from '../theme/index.js';
import type {
  ApplyDeltaOptions,
  DeltaMeta,
  ExportOptions,
  ExportResult,
  InstrumentOptions,
  JsonValue,
  KleinInstrument,
  LoadOptions,
  ValidationResult,
  Vector2,
  View2D,
} from '../core/index.js';
import {
  escapePdfText,
  pdfDocument,
  pdfFillColor,
  pdfNumber,
  pdfStrokeColor,
  pdfText,
  svgToPngBlob,
} from '../export/index.js';
import {
  buildAngleBisector2D,
  buildCircleByCenterPoint2D,
  buildCircleThroughPoints2D,
  buildConstructedLine2D,
  buildIntersection2D,
  buildLineThroughPoints2D,
  buildMidpoint2D,
  constrainGeometryScene,
  geometryAdjustSegmentLength as adjustSegmentLength,
  geometryLineConstraintPointIds as lineConstraintPointIds,
  geometrySegmentLength as segmentLength,
  geometrySetCircleRadius as setCircleRadius,
  geometrySetPointOnAngle as setPointOnAngle,
  geometrySetPointPosition as setPointPosition,
  buildGeometryDependencyGraph,
  buildGeometryObjectPanelRows,
  createEmptyGeometryScene,
  distance2D,
  geometryAngleBisectorPoint2D,
  geometryConstraintDependencies,
  geometryConstructionSourceIds,
  geometryCircleTangentPoint2D,
  geometryDependentsOf,
  geometryCircumcircle2D,
  geometryEntityPointIds,
  geometryIntersectionPoint2D,
  geometryIntersectionPoints2D,
  geometryLine3DForEntity,
  geometryLineLikeIntersection2D,
  geometryLinePlaneIntersection3D,
  geometryObjectDependencies,
  geometryPlaneEquation3D,
  geometryPlanePlaneIntersection3D,
  lineEquationFrom2DPoints,
  midpoint2D,
  normalizeGeometryLineEquation,
  normalizeGeometryPlaneEquation3D,
  planeEquationFrom3DPoints,
  recomputeGeometryDependents,
  recomputeGeometryScene,
  summarizeGeometryConstraints,
  summarizeGeometryObjects,
} from '../geometry-core/index.js';
import type {
  AngleEntity,
  ArcEntity,
  CircleEntity,
  ConicEntity,
  GeometryConstraint,
  GeometryConstraintSummary,
  GeometryConicEquation,
  GeometryConstruction,
  GeometryCoreSnapshot,
  GeometryDependencyGraph,
  GeometryDimension,
  GeometryEntity,
  GeometryEntityDisplay,
  GeometryLine3D,
  GeometryLineEquation,
  GeometryObjectPanelOptions,
  GeometryObjectPanelRow,
  GeometryObjectSummary,
  GeometryObjectSummaryOptions,
  GeometryPoint,
  GeometryPoint2D,
  GeometryPoint3D,
  GeometryPlaneEquation3D,
  GeometryScene,
  LineEntity,
  LocusEntity,
  ParametricCurveEntity,
  PlaneEntity,
  PolygonEntity,
  RayEntity,
  GeometryRelationMarkerEntity,
  SegmentEntity,
  VectorEntity,
} from '../geometry-core/index.js';


export {
  buildGeometryDependencyGraph,
  buildGeometryObjectPanelRows,
  createEmptyGeometryScene,
  distance2D,
  geometryAngleBisectorPoint2D,
  geometryCircleTangentPoint2D,
  geometryConstraintDependencies,
  geometryConstructionSourceIds,
  geometryDependentsOf,
  geometryCircumcircle2D,
  geometryEntityPointIds,
  geometryIntersectionPoint2D,
  geometryIntersectionPoints2D,
  geometryLine3DForEntity,
  geometryLineLikeIntersection2D,
  geometryLinePlaneIntersection3D,
  geometryObjectDependencies,
  geometryPlaneEquation3D,
  geometryPlanePlaneIntersection3D,
  lineEquationFrom2DPoints,
  midpoint2D,
  normalizeGeometryLineEquation,
  normalizeGeometryPlaneEquation3D,
  planeEquationFrom3DPoints,
  recomputeGeometryDependents,
  recomputeGeometryScene,
  summarizeGeometryConstraints,
  summarizeGeometryObjects,
};

export type {
  AngleEntity,
  ArcEntity,
  CircleEntity,
  ConicEntity,
  GeometryConstraint,
  GeometryConstraintSummary,
  GeometryConicEquation,
  GeometryConstruction,
  GeometryCoreSnapshot,
  GeometryDependencyGraph,
  GeometryDimension,
  GeometryEntity,
  GeometryEntityDisplay,
  GeometryLine3D,
  GeometryLineEquation,
  GeometryObjectPanelOptions,
  GeometryObjectPanelRow,
  GeometryObjectSummary,
  GeometryObjectSummaryOptions,
  GeometryPoint,
  GeometryPoint2D,
  GeometryPoint3D,
  GeometryPlaneEquation3D,
  GeometryScene,
  LineEntity,
  LocusEntity,
  ParametricCurveEntity,
  PlaneEntity,
  PolygonEntity,
  RayEntity,
  GeometryRelationMarkerEntity,
  SegmentEntity,
  VectorEntity,
};


export {
  applyGeometryCalculatorDelta,
  clampGeometryZoom,
  createEmptyGeometryCalculatorSnapshot,
  parseGeometryCalculatorSnapshotJson,
  screenToGeometryWorld,
  validateGeometryCalculatorSnapshot,
  geometryWorldToScreen,
} from './snapshot.js';
export {
  lineEquationFromPoints,
  parseGeometryCircleEquation,
  parseGeometryLineEquation,
} from './equations.js';
export { angleMeasureDegrees } from './geometry-math.js';
export { createGeometryCalculator } from './instrument.js';
export type {
  AngleCreationOptions,
  GeometryAngleOptions,
  GeometryCalculator,
  GeometryCalculatorAppState,
  GeometryCalculatorDelta,
  GeometryCalculatorOptions,
  GeometryCalculatorScene,
  GeometryCalculatorSelectable,
  GeometryCalculatorSelection,
  GeometryCalculatorSnapshot,
  GeometryCalculatorTheme,
  GeometryCalculatorThemeInput,
  GeometryCalculatorThemeName,
  GeometryCalculatorTool,
  GeometryCheckpoint,
  GeometryCircleEquation,
  GeometryConstraintDraft,
  GeometryConicOptions,
  GeometryGridOptions,
  GeometryGridOptionsPatch,
  GeometryHistoryEntry,
  GeometryLocusOptions,
  GeometryObjectEditOptions,
  GeometryObjectGroup,
  GeometryParametricCurveOptions,
  GeometryReflectionAxis,
  GeometryRelationMarkerKind,
  GeometryShapeKind,
  GeometrySnapKind,
  GeometrySnapModes,
  GeometrySnapSettings,
  GeometrySnapSettingsPatch,
  GeometryStyleOptions,
  GeometryTriangleClassification,
  ShapeCreationOptions,
} from './types.js';
