export * from './core/index.js';

export {
  applyKleinToolTheme,
  getKleinToolThemeCssVariables,
  KLEIN_DARK_TOOL_THEME,
  KLEIN_LIGHT_TOOL_THEME,
  resolveKleinToolTheme,
} from './theme/index.js';
export type {
  KleinToolTheme,
  KleinToolThemeInput,
  KleinToolThemeName,
  KleinToolThemeTarget,
} from './theme/index.js';

export {
  createMathCore,
} from './math/index.js';
export type {
  BinaryNode,
  EquationNode,
  FunctionCallNode,
  InequalityNode,
  MathCore,
  MathEvaluateOptions,
  MathNode,
  MathParseResult,
  MathValue,
  MatrixNode,
  NumberNode,
  SymbolNode,
  UnaryNode,
  VectorNode,
} from './math/index.js';

export {
  buildGeometryDependencyGraph,
  buildGeometryObjectPanelRows,
  createEmptyGeometryScene,
  distance2D,
  geometryAngleBisectorPoint2D,
  geometryCircleTangentPoint2D,
  geometryConstraintDependencies,
  geometryConstructionSourceIds,
  geometryCircumcircle2D,
  geometryDependentsOf,
  geometryEntityPointIds,
  geometryIntersectionPoint2D,
  geometryIntersectionPoints2D,
  geometryLine3DForEntity,
  geometryLineLikeIntersection2D,
  geometryLinePlaneIntersection3D,
  geometryObjectDependencies,
  geometryPlaneEquation3D,
  geometryPlanePlaneIntersection3D,
  lineEquationFrom2DPoints,
  midpoint2D,
  normalizeGeometryLineEquation,
  normalizeGeometryPlaneEquation3D,
  planeEquationFrom3DPoints,
  recomputeGeometryDependents,
  recomputeGeometryScene,
  summarizeGeometryConstraints,
  summarizeGeometryObjects,
} from './geometry-core/index.js';
export type {
  AngleEntity,
  ArcEntity,
  CircleEntity,
  ConicEntity,
  GeometryConstraint,
  GeometryConstraintSummary,
  GeometryConicEquation,
  GeometryConstruction,
  GeometryCoreSnapshot,
  GeometryDependencyGraph,
  GeometryDimension,
  GeometryEntity,
  GeometryEntityDisplay,
  GeometryLine3D,
  GeometryLineEquation,
  GeometryObjectPanelOptions,
  GeometryObjectPanelRow,
  GeometryObjectSummary,
  GeometryObjectSummaryOptions,
  GeometryPoint,
  GeometryPoint2D,
  GeometryPoint3D,
  GeometryPlaneEquation3D,
  GeometryScene,
  LineEntity,
  LocusEntity,
  ParametricCurveEntity,
  PlaneEntity,
  PolygonEntity,
  RayEntity,
  GeometryRelationMarkerEntity,
  SegmentEntity,
  VectorEntity,
} from './geometry-core/index.js';

export {
  angleMeasureDegrees,
  applyGeometryCalculatorDelta,
  clampGeometryZoom,
  createEmptyGeometryCalculatorSnapshot,
  createGeometryCalculator,
  geometryWorldToScreen,
  lineEquationFromPoints,
  parseGeometryCalculatorSnapshotJson,
  parseGeometryLineEquation,
  screenToGeometryWorld,
  validateGeometryCalculatorSnapshot,
} from './geometry/index.js';
export type {
  AngleCreationOptions,
  GeometryAngleOptions,
  GeometryCalculator,
  GeometryCalculatorAppState,
  GeometryCalculatorDelta,
  GeometryCheckpoint,
  GeometryCalculatorOptions,
  GeometryCalculatorScene,
  GeometryCalculatorSelection,
  GeometryCalculatorSnapshot,
  GeometryCalculatorTheme,
  GeometryCalculatorThemeInput,
  GeometryCalculatorThemeName,
  GeometryConicOptions,
  GeometryCalculatorTool,
  GeometryConstraintDraft,
  GeometryGridOptions,
  GeometryHistoryEntry,
  GeometryLocusOptions,
  GeometryParametricCurveOptions,
  GeometryRelationMarkerKind,
  GeometryShapeKind,
  GeometryStyleOptions,
  GeometryTriangleClassification,
  ShapeCreationOptions,
} from './geometry/index.js';

export {
  applyWhiteboardDelta,
  compactWhiteboardDeltas,
  createCompactedWhiteboardDelta,
  createEmptyWhiteboardSnapshot,
  createWhiteboard,
  createWhiteboardEmbeddedCardElement,
  createWhiteboardObjectComment,
  createWhiteboardPresenceOverlay,
  createWhiteboardRuntime,
  exportWhiteboardFrameSvg,
  exportWhiteboardSvg,
  getWhiteboardToolDefinitions,
  validateWhiteboardDelta,
  validateWhiteboardSnapshot,
} from './whiteboard/index.js';
export type {
  CompactWhiteboardDeltasOptions,
  CreateWhiteboardEmbeddedCardInput,
  EmbeddedSnapshotCardElement,
  LineElement,
  ShapeElement,
  StickyElement,
  StrokeElement,
  TextElement,
  WhiteboardEmbeddedToolKey,
  WhiteboardFrameExportOptions,
  WhiteboardAppState,
  WhiteboardDelta,
  WhiteboardElement,
  WhiteboardElementBase,
  WhiteboardObjectComment,
  WhiteboardOptions,
  WhiteboardOverlayBounds,
  WhiteboardPresenceOverlay,
  WhiteboardPresenceOverlayInput,
  WhiteboardScene,
  WhiteboardSvgExportOptions,
  WhiteboardSnapshot,
  WhiteboardToolDefinition,
  WhiteboardTool,
} from './whiteboard/index.js';

export {
  applyGeometryLabDelta,
  assertGeometryLabCommandComplexity,
  assertGeometryLabDeltaComplexity,
  assertGeometryLabExportOutputComplexity,
  assertGeometryLabExportRequestComplexity,
  buildGeometryLabDependencyGraph,
  canonicalizeGeometryLabSnapshot,
  compactGeometryLabDelta,
  compactGeometryLabSnapshot,
  compileEquationSurface3D,
  createEmptyGeometryLabSnapshot,
  createGeometryLab,
  DEFAULT_GEOMETRY_LAB_COMPLEXITY_LIMITS,
  DEFAULT_SURFACE_DISCONTINUITY_POLICY_3D,
  createGeometryLabRuntime,
  defaultGeometryCamera3D,
  geometryLabDependencyKey,
  geometryLabDependencyRefsForId,
  geometryLabStoredCollections,
  getGeometryLabInvariantIssues,
  GEOMETRY_LAB_MAX_SURFACE_GRID_SAMPLES,
  GEOMETRY_LAB_MAX_SURFACE_PROBE_EVALUATIONS,
  GEOMETRY_LAB_MAX_SURFACE_SAMPLES_PER_AXIS,
  GEOMETRY_LAB_SURFACE_CONTINUITY_SUBDIVISIONS,
  GeometryLabCanonicalizationError,
  assertGeometryLabJsonInputComplexity,
  assertGeometryLabSnapshotComplexity,
  estimateGeometryLabSurfaceProbeEvaluations,
  parseGeometryLabSnapshotJson,
  planGeometryLabCascadeDeletion,
  reduceGeometryLabDelta,
  renderGeometryLabSvg3D,
  preflightGeometryLabCommandComplexity,
  preflightGeometryLabDeltaComplexity,
  preflightGeometryLabExportOutputComplexity,
  preflightGeometryLabExportRequestComplexity,
  preflightGeometryLabJsonInputComplexity,
  preflightGeometryLabSnapshotComplexity,
  resolveGeometryLabComplexityLimits,
  sampleRectangularSurface3D,
  surfaceGridIndex3D,
  assertGeometryLabInvariants,
  validateGeometryLabCommand,
  validateGeometryLabDelta,
  validateGeometryLabSnapshot,
} from './geometry-lab/index.js';
export type {
  CompiledEquationSurface3D,
  CrossSectionEntity,
  EquationAxis3D,
  EquationSurfaceInput3D,
  GeometryCameraPreset3D,
  GeometryLabCascadeDeletePlan,
  GeometryLabCanonicalizationErrorCode,
  GeometryLabComplexityIssue,
  GeometryLabComplexityIssueCode,
  GeometryLabComplexityLimits,
  GeometryLabComplexityResult,
  GeometryLabCommand,
  GeometryLabDeleteBlocker,
  GeometryLabDependencyCollection,
  GeometryLabDependencyDeletePolicy,
  GeometryLabDependencyEdge,
  GeometryLabDependencyGraph,
  GeometryLabDependencyKey,
  GeometryLabDependencyNode,
  GeometryLabDependencyRef,
  GeometryLabDependencyRelation,
  GeometryEntity3D,
  GeometryLab,
  GeometryLabAppState,
  GeometryLabDelta,
  GeometryLabHistoryPatch,
  GeometryLabHistoryRef,
  GeometryLabHistoryValue,
  GeometryLabOptions,
  GeometryLabReductionResult,
  GeometryLabScene,
  GeometryLabSnapshot,
  GeometryLabStyleOptions,
  GeometryLabTool,
  GeometryLabNodeDeletePolicy,
  GeometryLabOwnershipConflict,
  GeometryLabOwnershipEdge,
  GeometryLabOwnershipRelation,
  GeometryLabStoredCollection,
  GeometryLabUnresolvedDependency,
  GeometryPolyhedronKind,
  GeometryScene2D,
  GeometryScene3D,
  GeometrySceneLink,
  GeometrySelection,
  Measurement3D,
  MeasurementSource3D,
  CurveEntity3D,
  ParametricCurve3DInput,
  RectangularSurfaceSamplingInput3D,
  SampledRectangularSurface3D,
  SolidCreationOptions,
  SolidEdge3D,
  SolidEntity,
  SolidFace3D,
  SolidNet3D,
  SolidNetFace2D,
  SolidParameters3D,
  SurfaceEntity3D,
  SurfaceDiscontinuityPolicy3D,
  SurfaceGridSampleValidity3D,
  SurfaceQuadFace3D,
  SurfaceSamplingAxis3D,
  SurfaceSamplingDiagnostics3D,
  SurfaceSamplingGrid3D,
  SurfaceZInput3D,
  WorkPlane3D,
  WorkPlaneSource3D,
} from './geometry-lab/index.js';

export {
  applyGraphingCalculatorDelta,
  createEmptyGraphingSnapshot,
  createGraphingCalculator,
  createGraphingRuntime,
  evaluateGraphExpression,
  findGraphIntersections,
  findGraphRoots,
  parseGraphExpression,
  parseGraphingSnapshotJson,
  sampleGraphExpression,
  validateGraphingDelta,
  validateGraphingSnapshot,
} from './graphing/index.js';
export type {
  GraphAnalysisPoint,
  GraphEvaluationOptions,
  GraphExpressionInputOptions,
  GraphExpressionKind,
  GraphExpression,
  GraphingCalculator,
  GraphPoint,
  GraphPointInputOptions,
  GraphPlotOptions,
  GraphPlotSegment,
  GraphSamplePoint,
  GraphSlider,
  GraphSliderInputOptions,
  GraphViewport,
  GraphingAppState,
  GraphingDelta,
  GraphingOptions,
  GraphingScene,
  GraphingSnapshot,
  GraphingTool,
  ParsedGraphExpression,
} from './graphing/index.js';

export {
  applyGraphing3DDelta,
  createEmptyGraphing3DSnapshot,
  createGraphing3DCalculator,
  createGraphing3DRuntime,
  parseGraphing3DSnapshotJson,
  validateGraphing3DDelta,
  validateGraphing3DSnapshot,
} from './graphing-3d/index.js';
export type {
  Graphing3DCalculator,
  Graphing3DCommand,
  Graphing3DDelta,
  Graphing3DOptions,
  Graphing3DSnapshot,
  Graphing3DTool,
} from './graphing-3d/index.js';

export {
  createAlgebraLab,
  createEmptyAlgebraSnapshot,
} from './algebra/index.js';
export type {
  AlgebraAppState,
  AlgebraDelta,
  AlgebraEntry,
  AlgebraOptions,
  AlgebraScene,
  AlgebraSnapshot,
  AlgebraStep,
  AlgebraTool,
} from './algebra/index.js';

export {
  applyCalculatorDelta,
  createEmptyCalculatorSnapshot,
  createScientificCalculator,
  createScientificCalculatorRuntime,
  validateCalculatorDelta,
  validateCalculatorSnapshot,
} from './calculator/index.js';
export type {
  CalculatorAppState,
  CalculatorDelta,
  CalculatorEntry,
  CalculatorOptions,
  CalculatorScene,
  CalculatorSnapshot,
  CalculatorTool,
  ScientificCalculator,
} from './calculator/index.js';

export {
  createEmptyScientificSnapshot,
} from './scientific/index.js';
export type {
  ScientificAppState,
  ScientificDelta,
  ScientificEntry,
  ScientificOptions,
  ScientificScene,
  ScientificSnapshot,
  ScientificTool,
} from './scientific/index.js';

export {
  applyProbabilityDelta,
  createEmptyProbabilitySnapshot,
  createProbabilityExplorer,
  createProbabilityRuntime,
  evaluateDistributionModel,
  validateProbabilityDelta,
  validateProbabilitySnapshot,
} from './probability/index.js';
export type {
  DistributionEvaluation,
  DistributionKind,
  DistributionModel,
  ProbabilityExplorer,
  ProbabilityAppState,
  ProbabilityDelta,
  ProbabilityOptions,
  ProbabilityScene,
  ProbabilitySnapshot,
  ProbabilityTool,
} from './probability/index.js';

export {
  KLEIN_V0_TOOLS,
  createKleinToolRuntime,
  getKleinToolDefinition,
  isKleinToolKey,
  normalizeKleinToolKey,
  requireKleinToolKey,
} from './tools/index.js';
export type {
  AnyKleinToolDelta,
  AnyKleinToolRuntime,
  AnyKleinToolSnapshot,
  CreateKleinToolRuntimeInput,
  CreateKleinToolRuntimeOptions,
  KleinToolAlias,
  KleinToolDefinition,
} from './tools/index.js';

export {
  createEmptySpreadsheetSnapshot,
  createSpreadsheet,
} from './spreadsheet/index.js';
export type {
  SpreadsheetAppState,
  SpreadsheetCell,
  SpreadsheetDelta,
  SpreadsheetOptions,
  SpreadsheetScene,
  SpreadsheetSnapshot,
  SpreadsheetTool,
} from './spreadsheet/index.js';

export {
  createEmptyWorkspaceSnapshot,
  createMathWorkspace,
} from './workspace/index.js';
export type {
  WorkspaceAppState,
  WorkspaceDelta,
  WorkspaceLink,
  WorkspaceOptions,
  WorkspacePanel,
  WorkspaceScene,
  WorkspaceSnapshot,
  WorkspaceTool,
} from './workspace/index.js';

export {
  appendReplayDelta,
  assignOwnershipColors,
  assertClassroomEditable,
  CLASSROOM_API_ROUTES,
  classroomDatasourceId,
  classroomModePolicy,
  classroomSessionMetadata,
  collectSnapshotObjectIds,
  createClassroomAssignment,
  createClassroomPolicy,
  createClassroomRuntime,
  createClassroomSessionId,
  createClassroomSessionState,
  createObjectComment,
  createReadOnlyShareLink,
  createStudentCopy,
  createTeacherReviewSnapshot,
  createTeacherTemplate,
  createTeamEditableSession,
  createTeamSessionId,
  freezeClassroomScene,
  listClassroomSessions,
  loadClassroomSession,
  lockSnapshotObjects,
  removeCollaborativeCursor,
  replayConstructionHistory,
  resolveObjectComment,
  saveClassroomSession,
  selectionToObjectIds,
  submitStudentWork,
  unfreezeClassroomScene,
  updateCollaborativeCursor,
} from './classroom/index.js';
export type {
  ClassroomAssignment,
  ClassroomAssignmentSettings,
  ClassroomAppendReplayInput,
  ClassroomContext,
  ClassroomEventListener,
  ClassroomFreezeState,
  ClassroomModePolicy,
  ClassroomObjectComment,
  ClassroomOwnership,
  ClassroomPolicy,
  ClassroomReviewSnapshot,
  ClassroomRuntime,
  ClassroomRuntimeEvent,
  ClassroomSaveDraftInput,
  ClassroomScope,
  ClassroomSetFrozenInput,
  ClassroomSessionKind,
  ClassroomSessionState,
  ClassroomShareLink,
  ClassroomStudentWork,
  ClassroomSubmitWorkInput,
  ClassroomTeacherTemplate,
  ClassroomWorkflowMode,
  ClassroomWorkflowRole,
  ClassroomWorkStatus,
  ConstructionReplayEvent,
  CreateClassroomAssignmentInput,
  CreateClassroomPolicyInput,
  CreateClassroomRuntimeInput,
  CreateClassroomSessionStateInput,
  CreateObjectCommentInput,
  CreateReadOnlyShareLinkInput,
  CreateReviewSnapshotInput,
  CreateStudentCopyInput,
  CreateTeacherTemplateInput,
  CreateTeamSessionInput,
  KleinClassroomBackendAdapter,
  ListClassroomSessionOptions,
  LoadClassroomSessionOptions,
  ObjectCommentInput,
  SaveClassroomSessionOptions,
  SubmissionResult,
  TeamEditableSession,
} from './classroom/index.js';

export {
  createKleinStorageAdapter,
  LocalStorageSessionAdapter,
  createLocalStorageSessionAdapter,
  loadInstrumentSession,
  migrateSnapshot,
  parseSnapshotJson,
  saveInstrumentSession,
  validateInstrumentSnapshot,
} from './persistence/index.js';
export type {
  KleinStorageAdapter,
  KleinSessionStorageAdapter,
  ListSessionsOptions,
  ListSnapshotsInput,
  LoadedSnapshot,
  LoadSnapshotInput,
  LocalStorageLike,
  LocalStorageSessionAdapterOptions,
  PersistedSession,
  SaveSessionInput,
  SaveSnapshotInput,
  SavedSnapshot,
  SnapshotSummary,
  SnapshotMigration,
} from './persistence/index.js';

export {
  bindCollaboration,
  bindRuntimeCollaboration,
  createDeltaMessage,
  createCollaborationWebSocketTransport,
  createCollaborationWebSocketUrl,
  createInMemoryCollaborationHub,
  createInMemoryCollaborationTransport,
  isDeltaMessage,
  parseCollaborationMessage,
  sendCollaborativeCursor,
  WebSocketCollaborationTransport,
} from './collab/index.js';
export type {
  CollaborativeCursor,
  CollaborationBinding,
  CollaborationConnectionState,
  CollaborationProtocolError,
  CollaborationSocketFactory,
  CollabMessage,
  CollaborationOptions,
  RuntimeCollaborationOptions,
  CollaborationRoomEvent,
  CollaborationSelectionItem,
  CollaborationTransport,
  CollaborationWebSocketLike,
  CollaborationWebSocketTransportOptions,
  CreateCollaborationWebSocketUrlInput,
  CreateDeltaMessageInput,
  InMemoryCollaborationTransportOptions,
  PresenceUser,
  PresenceEvent,
  ReconnectPolicy,
} from './collab/index.js';

export {
  defineKleinElements,
  KLEIN_ELEMENT_TAGS,
} from './dom/index.js';

export {
  createEmbedUrl,
  createHostBridge,
  parseEmbedSearchParams,
  verifyEmbeddedLaunchContext,
} from './embed/index.js';
export type {
  EmbeddedLaunchContext,
  EmbeddedLaunchContextVerification,
  EmbeddedMode,
  EmbeddedPlatform,
  EmbeddedToolKind,
  EmbedUrlOptions,
  HostBridge,
  HostBridgeMessage,
  HostBridgeOptions,
  VerifyEmbeddedLaunchContextOptions,
} from './embed/index.js';

export {
  assertExamCommandAllowed,
  createExamController,
  EXAM_API_ROUTES,
  examPolicyDecision,
  watchBrowserExamIntegrity,
} from './exam/index.js';
export type {
  BrowserExamIntegrityWatcherOptions,
  CreateExamControllerOptions,
  ExamController,
  ExamDisabledFeature,
  ExamEventListener,
  ExamIntegrityEvent,
  ExamIntegrityEventKind,
  ExamProfile,
  ExamSession,
  ExamSessionStatus,
  ExamStopReason,
} from './exam/index.js';

export {
  createClassroomAddonRouteConfig,
  createClassroomIframeUrl,
  createTeamsManifestTemplate,
  createTeamsTabUrl,
  modeForClassroomIframe,
  TEAMS_MANIFEST_VERSION,
} from './integrations/index.js';
export type {
  ClassroomAddonRouteConfig,
  ClassroomAttachment,
  ClassroomIframeKind,
  ClassroomLaunchContext,
  ClassroomRole,
  ClassroomUrlOptions,
  TeamsLaunchContext,
  TeamsManifestDeveloper,
  TeamsManifestOptions,
  TeamsManifestTemplate,
  TeamsSurface,
  TeamsTabUrlOptions,
} from './integrations/index.js';
